In [1]:
import pprint
import numpy as np
from spelling_correction_models.elmo_40in_spelling_corrector.elmo_40in2_spelling_corrector import ELMO40in2SpellingCorrector
from copy import deepcopy
from spelling_correction_models.elmo_40in_spelling_corrector.helper_fns import *


/home/alx/Cloud/spell_corr/py_spelling_corrector


In [2]:
elmo40in = ELMO40in2SpellingCorrector(mini_batch_size=10)
# sccg = elmo40in.sccg

Init LetterCaser.
Init language_model.


[nltk_data] Downloading package punkt to /home/alx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/alx/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /home/alx/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/alx/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
2019-11-11 11:14:28.501 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:21: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2019-11-11 11:14:28.502 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:21: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO 

/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news
['/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003.meta']
/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003.meta
/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003


2019-11-11 11:14:32.713 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:40: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-11-11 11:14:32.713 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-11-11 11:14:32.996 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:43: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2019-11-11 11:14:32.997 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:158: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder inst

USING SKIP CONNECTIONS


2019-11-11 11:14:33.430 WARNING in 'tensorflow'['ag_logging'] at line 145: Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f98880d51d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7f98880d51d0>>: AttributeError: module 'gast' has no attribute 'Num'
2019-11-11 11:14:33.458 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:52: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-11-11 11:14:33.484 WARNING in 'tensorflow'['deprecation'] at line 323: From /home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/tensorflow/python/training/save

KeyboardInterrupt: 

# Manual Debugging of Analysis Dictionary Construction

In [3]:
# sentence = "мамо мы ла рабу"
sentence = "мама что нибудь скажет"
# sentence = "мама что нибуть скажет"
sentence = "очень классная тетка ктобы что не говорил"
# sentence ="расжился на выходных экземпляром сабжа"
# sentence = "съездеть чтоль в музей какой коли они все сегодня бесплатные"
# sentence ='сегоднямрачная погода'

# 'golden_sentence': 'симпатичнейшее шпионское устройство такой себе гламурный '
#                     'фотоаппарат девушки бонда миниатюрная модель камеры '
#                     'superheadz clap camera',
sentence = 'симпатичнейшое шпионское устройство такой себе гламурный фотоаппарат девушки бонда миниатюрная модель камеры superheadz clap camera'
sentence = "ну не было поста так небыло"
sentence = "пояним эту мысль"
sentence = "полчатся вот такие язычки"
sentence = "вобщем как вы знаете из моего не давнего поста я жаловался на пропажу писем с моего ящека на почте.ру"
# sentence = "а рите снятся сны в которых меня убивают патаму шта я пытаюсь всех спасти"
# sentence = "а днем мама снится как будто мы с ней в соре и она мне чтото выговаривает"
# sentence = "интересно чтобы было еслиб этот фильм посмотреела бы с димой"
# sentence = "так вот я боюсь подержанную потомучто меня провести как нефиг делать"
# sentence = "седня должен был на работу притащиться программист и вешать всем оплеух причем большую часть на меня"
# sentence = "сегодня должен был на работу притащиться программист и навешать всем оплеух причем большую часть на меня"
# sentence = "ограничте время между кликами что-ли"
# sentence = "начальнег зажог павзрослому всю предудущую неделю ходил покрытый прыщами а с понедельника слег ветрянка"
# sentence = "подсаживаеться женшина иностранка из норвегии она приглашает меня танцевать оказывается что это место слишком крутое для меня я загруживаюсь и больше в этот вечер не танцую"
# sentence = "ощушаю себя с ними монголойдом я никогда так много не молчала как молчю тут и не потому что языковый баръер или еще что-то просто коментариев нет"
# sentence = "атличный лотос у тебя"
# sentence = "обълись пиццы и всячески ввеселились"
# sentence = "распрашивая иностранцев-гостей питера о их впечатлении от русских частым комментарием был тот факт что все слишком сердитые и серьезные никто не улыбается на улице"
# sentence = "зашел в в какой-то сетевой европейский не помню название бренда магазин купить сыну игрушку из командировки lego цены московские девченки-продавцы по-русски говорят плохо"
# sentence = "зубодробительня гребенка с острыми камнями на протяжении всех 50 км пути"
# sentence = "прийдя в мгту я был удивлен никого необноружив там"
# sentence = "профессиональнаякарьера патрисии началась чтовполне закономерно недалеко от родных мест но за пределами франции"
# sentence = "иногда даже приятно что выходные закончились и можно вздохнуть спокойно d"
# sentence = "он становится безупречнее день ото дня вот о чем я"
sentence = "вообщем ты добрее чем я"
# sentence = "прищлось ответить что случайно не я"
# sentence = 'настроене не понятное какоето солено-сладкое с одной стороны жалко расставаться с родителями и другими близкими людьми с другой радость от наконецто сбывающеся мечты можно и так это назвать хотя скорее стремление к более спокойной жизни ну и для меня лично есть огромная доля приключения в этом всем это как минимум интересно я всегда мечтал о таком путешествии вот так сижу обуреваемый чувствами'

In [ ]:
output_sentences_kek = elmo40in.process_sentences_batch([sentence], min_advantage_treshold=1.0, max_tokens_count=4900)n

dynamic batch size: 1
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(124)_mini_batch_fit()
    123         # time major
--> 124         batch = np.expand_dims(self.batcher.batch_sentences(batch).transpose(1,0,2), axis=2)
    125         batch_reverse = np.expand_dims(self.batcher.batch_sentences(batch_reverse).transpose(1,0,2), axis=2)

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(125)_mini_batch_fit()
    124         batch = np.expand_dims(self.batcher.batch_sentences(batch).transpose(1,0,2), axis=2)
--> 125         batch_reverse = np.expand_dims(self.batcher.batch_sentences(batch_reverse).transpose(1,0,2), axis=2)
    126 

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(127)_mini_batch_fit()
    126 
--> 127         pad_size = self.mini_batch_size - batch.shape[1]
    128 

ipdb> batch_reverse
array([[[[258., 256., 259., 260., 260., 260., 260., 260., 260., 260.,


ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(136)_mini_batch_fit()
    135             #batch padding
--> 136             complete_batch = np.pad(time_sliced_batch, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
    137             complete_batch_reverse = np.pad(time_sliced_batch_reverse, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(137)_mini_batch_fit()
    136             complete_batch = np.pad(time_sliced_batch, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
--> 137             complete_batch_reverse = np.pad(time_sliced_batch_reverse, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
    138 

ipdb> complete_batch
array([[[258., 256., 259., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]],

       ...,

       [[260.

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(141)_mini_batch_fit()
    140             feed_dict[self.model.tokens_characters] = complete_batch
--> 141             feed_dict[self.model.tokens_characters_reverse] = complete_batch_reverse
    142             start_dt = dt.datetime.now()

ipdb> self.model.tokens_characters
<tf.Tensor 'lm/tokens_characters:0' shape=(330, 1, 50) dtype=int64>
ipdb> complete_batch
array([[[258., 256., 259., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]],

       ...,

       [[260., 260., 260., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]],

       [[260., 260., 260., ..., 260., 260., 260.]]])
ipdb> complete_batch.shape
(330, 1, 50)
ipdb> complete_batch[:10]
array([[[258., 256., 259., 260., 260., 260., 260., 260., 260., 260.,
         260., 260., 260., 260., 260., 260., 260., 260., 260., 260.,
         

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(142)_mini_batch_fit()
    141             feed_dict[self.model.tokens_characters_reverse] = complete_batch_reverse
--> 142             start_dt = dt.datetime.now()
    143             ret = self.sess.run([self.model.individual_output_softmaxes, final_state_tensors],

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(143)_mini_batch_fit()
    142             start_dt = dt.datetime.now()
--> 143             ret = self.sess.run([self.model.individual_output_softmaxes, final_state_tensors],
    144                                 feed_dict=feed_dict

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(144)_mini_batch_fit()
    143             ret = self.sess.run([self.model.individual_output_softmaxes, final_state_tensors],
--> 144                                 feed_dict=feed_dict
    145                                 )


ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(139)_mini_batch_fit()
    138 
--> 139             feed_dict = {t: v for t, v in zip(init_state_tensors, init_state_values)}
    140             feed_dict[self.model.tokens_characters] = complete_batch

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(140)_mini_batch_fit()
    139             feed_dict = {t: v for t, v in zip(init_state_tensors, init_state_values)}
--> 140             feed_dict[self.model.tokens_characters] = complete_batch
    141             feed_dict[self.model.tokens_characters_reverse] = complete_batch_reverse

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(141)_mini_batch_fit()
    140             feed_dict[self.model.tokens_characters] = complete_batch
--> 141             feed_dict[self.model.tokens_characters_reverse] = complete_batch_reverse
    142             start_dt = dt.datetime.now()

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(136)_mini_batch_fit()
    135             #batch padding
--> 136             complete_batch = np.pad(time_sliced_batch, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
    137             complete_batch_reverse = np.pad(time_sliced_batch_reverse, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(137)_mini_batch_fit()
    136             complete_batch = np.pad(time_sliced_batch, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
--> 137             complete_batch_reverse = np.pad(time_sliced_batch_reverse, ((0,pad_size),(0,0),(0,0)), 'constant',constant_values=260)
    138 

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(139)_mini_batch_fit()
    138 
--> 139             feed_dict = {t: v for t, v in zip(init_state_tensors, init_state_

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(143)_mini_batch_fit()
    142             start_dt = dt.datetime.now()
--> 143             ret = self.sess.run([self.model.individual_output_softmaxes, final_state_tensors],
    144                                 feed_dict=feed_dict

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(144)_mini_batch_fit()
    143             ret = self.sess.run([self.model.individual_output_softmaxes, final_state_tensors],
--> 144                                 feed_dict=feed_dict
    145                                 )

ipdb> n
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo_bilm.py(146)_mini_batch_fit()
    145                                 )
--> 146             fin_dt = dt.datetime.now()
    147             print("datetimes. tf time sess.run %s" % (str(fin_dt - start_dt)))

ipdb> 
> /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectio

In [ ]:
# elmo40in.lm.elmo_lm([["вообщем", "ты","добрее","чем", "я"]])
# elmo40in.lm.elmo_lm([["вообщем", "ты","добрее","чем", "я"]])
# out_mat1 = elmo40in.lm.analyze_sentence("Привет ватрушка")
out_mat1 = elmo40in.lm.analyze_sentence("мама мыла раму")

print(out_mat1.shape)
out_mat1

In [ ]:
################## TorchLM ################################################

In [1]:
from language_models.elmolm_on_torch import ELMOLMTorch
torch_lm = ELMOLMTorch()

In [2]:
torch_lm.elmo_lm([["пояним", "эту", "мысль"]])

array([[[[ 8.698505  , 10.531436  , 11.591449  , ..., -3.3195941 ,
           0.20911525, -1.324028  ],
         [11.663498  ,  6.4896927 , 13.29825   , ..., -3.7969227 ,
          -0.7981506 , -0.5706822 ]],

        [[11.197303  , 13.643537  , 13.771962  , ..., -2.2908905 ,
           0.9362528 , -1.8214061 ],
         [15.099113  ,  8.962275  , 14.453609  , ..., -3.2035878 ,
          -0.26868254, -1.9468111 ]],

        [[10.3292265 ,  9.750019  , 14.992222  , ..., -0.13901873,
          -0.5180782 , -1.68019   ],
         [10.416851  ,  8.0629225 , 13.751131  , ..., -2.1640732 ,
          -0.23396371, -0.76373714]],

        [[ 9.719891  , 17.389019  , 14.705378  , ..., -1.5197084 ,
           1.1005607 , -1.3403838 ],
         [ 9.967672  ,  9.125053  , 14.253396  , ..., -1.5328779 ,
           2.9189599 , -0.3669657 ]],

        [[11.777227  , 16.810158  , 15.647517  , ..., -0.3641121 ,
          -1.7544152 , -0.7777235 ],
         [13.162939  ,  7.1723986 , 13.992031  , ..., -3

In [3]:
# out_mat = torch_lm.analyze_sentence("Привет ватрушка")
# out_mat = torch_lm.analyze_sentence("пояним эту мысль")
out_mat = torch_lm.analyze_sentence('что-нить наидем в этой деревне')

print(out_mat.shape)
out_mat

(7, 2, 1000000)


array([[[ 8.579025  , 10.255845  , 12.490642  , ..., -1.9031111 ,
         -0.22491021, -0.8162353 ],
        [11.516237  ,  7.0997515 , 13.842033  , ..., -3.6547234 ,
         -0.920868  , -1.5131917 ]],

       [[10.171051  , 11.94821   , 13.493526  , ..., -2.470616  ,
          0.39267704, -1.2321949 ],
        [15.118414  ,  8.421725  , 14.220245  , ..., -3.087981  ,
         -1.2405609 , -1.5639873 ]],

       [[11.353952  , 16.822805  , 13.998278  , ..., -1.6403688 ,
         -0.07480513, -1.0404723 ],
        [14.039552  ,  7.665844  , 14.076542  , ..., -3.9395056 ,
         -1.1204051 , -2.2891538 ]],

       ...,

       [[10.540981  , 12.596955  , 15.792664  , ..., -0.8537992 ,
         -2.9171567 , -2.1345274 ],
        [11.732328  ,  8.346748  , 13.950236  , ..., -3.8719285 ,
         -1.408975  , -2.1800478 ]],

       [[10.9180355 , 17.91484   , 14.347364  , ..., -2.6076658 ,
         -1.090107  , -0.5447088 ],
        [ 9.813944  ,  7.4901476 , 14.332923  , ..., -3.21553

In [116]:
idx_0 = torch_lm.get_word_idx("<UNK>")
idx_0

2

In [110]:
idx = torch_lm.get_word_idx("поясним")
idx

221828

In [120]:
out_mat[1, idx]

8.087805

In [121]:
out_mat[1, idx_0]

17.445087

In [126]:
out_mat[0]

(1000000,)

In [127]:
list[2]

TypeError: 'type' object is not subscriptable

In [4]:
def find_top_k_word_idxes_for_elmo_mat(elmo_mat, col_idx, top_k=10):
    column = elmo_mat[col_idx]
    sorted_indexes = column.argsort()
    print(sorted_indexes[-top_k:])
    return sorted_indexes[-top_k:]

def find_top_k_words_for_elmo_mat(elmo_mat, col_idx, words, top_k=10):
    sorted_indexes = find_top_k_word_idxes_for_elmo_mat(elmo_mat, col_idx, top_k=10)
    
    return [words[idx] for idx in sorted_indexes]
find_top_k_words_for_elmo_mat(out_mat, 3, torch_lm.words)

[[ 67519  83010  81295 ...    131   1538      2]
 [504715 154584 262844 ...      2    231   1233]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [131]:
out_mat[1][829]

23.76736

In [14]:
torch_lm.tokenize_sentence("Привет ватрушка")

['<S>', 'Привет', 'ватрушка', '</S>']

In [5]:
out_mat.shape

(6, 1000000)

In [8]:
torch_lm.get_word_idx_or_unk("лошара")

(794206, False)

In [145]:
from allennlp.modules.elmo import batch_to_ids

In [147]:
batch_to_ids(torch_lm.tokenize_sentence("Привет ватрушка"))

tensor([[[259, 209, 160, 260, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 210, 129, 260, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 209, 185, 260, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 261],
         [259, 209, 179, 260, 261, 261, 261, 261, 261, 261, 261, 261, 261, 261,
          261, 261, 261, 261, 261, 261, 261, 26

In [7]:
output_sentences_kek = elmo40in.process_sentences_batch([[sentence]], min_advantage_treshold=1.0, max_tokens_count=4900)

AttributeError: 'list' object has no attribute 'split'

In [2]:
import torch

In [5]:
m = torch.nn.Softmax(dim=1)
input11 = torch.randn(2, 3)
print(input11)
output = m(input11)
output

tensor([[-0.8721,  0.7131, -0.8809],
        [ 0.8462,  1.1814,  0.0990]])


tensor([[0.1455, 0.7102, 0.1443],
        [0.3482, 0.4869, 0.1649]])

In [13]:
data = elmo40in.lm.elmo_lm([['вообщем', 'ты', 'добрее']])
print(data[0].shape)
data

datetimes. tf time sess.run 0:00:00.586216
datetimes. tf time sess.run 0:00:00.564711
datetimes. tf time sess.run 0:00:00.580774
datetimes. tf time sess.run 0:00:00.567486
datetimes. tf time sess.run 0:00:00.572802
datetimes. tf time 0:00:00.575775
(3, 2, 1000000)


[array([[[2.98011262e-04, 1.85721205e-03, 1.25587806e-02, ...,
          7.73374165e-09, 4.24469597e-08, 2.60588475e-08],
         [1.32069260e-01, 2.53366743e-04, 1.78584661e-02, ...,
          2.77909917e-09, 2.71196821e-09, 2.38465536e-09]],
 
        [[2.11240724e-04, 4.98192385e-03, 4.45203623e-03, ...,
          1.93698901e-09, 2.06664179e-08, 1.53979709e-08],
         [6.77132234e-03, 8.03239091e-05, 1.01086777e-02, ...,
          3.85685650e-10, 2.84415091e-09, 1.50535728e-09]],
 
        [[1.62894445e-04, 3.44465463e-03, 2.25659329e-02, ...,
          2.10931472e-09, 2.57905448e-08, 6.61500055e-09],
         [1.31442735e-03, 3.98670018e-05, 2.06014384e-02, ...,
          5.47498313e-09, 1.96581951e-08, 1.67768395e-08]]])]

In [4]:
# with uptrained
# elmo40in.prepare_analysis_dict_for_sentence("что-нить наидем")
elmo40in.prepare_analysis_dict_for_sentence("у нас всегда достанет сил чтобы перенести несчастье ближнего")


{'input_sentence': 'что-нить наидем',
 'tokenized_input_sentence': ['<S>', 'что-нить', 'наидем', '</S>'],
 'word_substitutions_candidates': [{'tok_idx': 0, 'top_k_candidates': []},
  {'tok_idx': 1,
   'top_k_candidates': [{'lm_advantage': 6.515989196619607,
     'advantage': 2.915989196619607,
     'token_str': 'что-нибудь',
     'zero_hypothesis': False,
     'error_score': -3.6,
     'token_merges': 0,
     'token_splits': None},
    {'lm_advantage': 0.0,
     'advantage': -1.0,
     'token_str': 'что-нить',
     'zero_hypothesis': True,
     'error_score': 0.0,
     'token_merges': 0,
     'token_splits': None},
    {'lm_advantage': 1.816925980036359,
     'advantage': -2.183074019963641,
     'token_str': 'что нить',
     'zero_hypothesis': False,
     'error_score': -4.0,
     'token_merges': 0,
     'token_splits': 1}]},
  {'tok_idx': 2,
   'top_k_candidates': [{'lm_advantage': 5.086796848406401,
     'advantage': 2.515360031222647,
     'token_str': 'найдем',
     'zero_hypothes

In [4]:
elmo40in.prepare_analysis_dict_for_sentence("что-нить наидем")

{'input_sentence': 'что-нить наидем',
 'tokenized_input_sentence': ['<S>', 'что-нить', 'наидем', '</S>'],
 'word_substitutions_candidates': [{'tok_idx': 0, 'top_k_candidates': []},
  {'tok_idx': 1,
   'top_k_candidates': [{'lm_advantage': 3.4535474998691793,
     'advantage': -0.14645250013082078,
     'token_str': 'что-нибудь',
     'zero_hypothesis': False,
     'error_score': -3.6,
     'token_merges': 0,
     'token_splits': None},
    {'lm_advantage': 0.0,
     'advantage': -1.0,
     'token_str': 'что-нить',
     'zero_hypothesis': True,
     'error_score': 0.0,
     'token_merges': 0,
     'token_splits': None},
    {'lm_advantage': 2.6473430629135457,
     'advantage': -1.3526569370864543,
     'token_str': 'что нить',
     'zero_hypothesis': False,
     'error_score': -4.0,
     'token_merges': 0,
     'token_splits': 1}]},
  {'tok_idx': 2,
   'top_k_candidates': [{'lm_advantage': 3.6374911611533065,
     'advantage': 0.8774911611533067,
     'token_str': 'на идем',
     'zero

In [ ]:
# elmo40in.process_sentence()

elmo40in.sccg([["что-нить"]])


In [ ]:
elmo40in.sccg([["вобщем"]])
# elmo40in.sccg([["в общем"]])


In [ ]:
elmo40in.sccg.searcher.search("в общем", d=2)

In [ ]:
elmo40in.sccg.searcher.transducer.operation_costs['в общем']

In [21]:
# elmo40in.process_sentence(sentence)
res_data = elmo40in.prepare_analysis_dict_for_sentence(sentence)

In [24]:
res_data['word_substitutions_candidates']

[{'tok_idx': 0, 'top_k_candidates': []},
 {'tok_idx': 1,
  'top_k_candidates': [{'lm_advantage': 5.042052588947163,
    'advantage': 1.0665896419827572,
    'token_str': 'настроены',
    'zero_hypothesis': False,
    'error_score': -3.975462946964406,
    'token_merges': 0,
    'token_splits': None},
   {'lm_advantage': 3.8491870035449143,
    'advantage': 0.8491870035449143,
    'token_str': 'настроен',
    'zero_hypothesis': False,
    'error_score': -3.0,
    'token_merges': 0,
    'token_splits': None},
   {'lm_advantage': 2.7373830048267074,
    'advantage': -0.06261699517329244,
    'token_str': 'настроение',
    'zero_hypothesis': False,
    'error_score': -2.8,
    'token_merges': 0,
    'token_splits': None},
   {'lm_advantage': 3.254557677609057,
    'advantage': -0.5504990413911113,
    'token_str': 'настроена',
    'zero_hypothesis': False,
    'error_score': -3.8050567190001683,
    'token_merges': 0,
    'token_splits': None},
   {'lm_advantage': 0.0,
    'advantage': -1.

In [26]:
list(map(lambda x: len(x['top_k_candidates']),res_data['word_substitutions_candidates']))

[0,
 8,
 1,
 10,
 5,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 1,
 2,
 4,
 1,
 4,
 6,
 1,
 1,
 4,
 2,
 4,
 3,
 1,
 1,
 2,
 4,
 1,
 2,
 1,
 7,
 4,
 1,
 1,
 4,
 1,
 1,
 7,
 9,
 3,
 4,
 2,
 1,
 1,
 1,
 1,
 6,
 1,
 6,
 5,
 3,
 5,
 5,
 2,
 4,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [ ]:
# debug sentence anlysis
preprocessed_sentence = elmo40in.preprocess_sentence(sentence)
elmo_data = elmo40in.lm.analyze_sentence(preprocessed_sentence)
analysis_dict = elmo40in.elmo_analysis_with_probable_candidates_reduction_dict_in_dict_out(
    {'input_sentence': preprocessed_sentence,
     'tokenized_input_sentence': elmo40in.lm.tokenize_sentence(preprocessed_sentence)}, 
    elmo_data,
    filter_by_lm_lower_bound=-16.0
)
merged_tokens_hypotheses_dict = elmo40in.generate_Nto1_hypotheses(analysis_dict['tokenized_input_sentence'], elmo_data)
# merged_tokens_hypotheses_dict
# analysis_dict
analysis_dict['word_substitutions_candidates'] += merged_tokens_hypotheses_dict
analysis_dict


In [ ]:
preprocessed_sentence = elmo40in.preprocess_sentence(sentence)
elmo_data = elmo40in.lm.analyze_sentence(preprocessed_sentence)

preprocessed_sentence

In [ ]:
# elmo40in.lm.get_word_idx_or_unk("симпатичнейшее")
# elmo40in.lm.get_word_idx_or_unk("димой")
elmo40in.lm.get_word_idx_or_unk("профессиональная")
# elmo40in.lm.get_word_idx_or_unk("карьера")

In [ ]:
elmo40in.lm.get_word_idx_or_unk("карьера")

In [ ]:
#################################################
analysis_dict= elmo40in.elmo_analysis_with_probable_candidates_reduction_dict_in_dict_out(
    {'input_sentence': preprocessed_sentence,
     'tokenized_input_sentence': elmo40in.lm.tokenize_sentence(preprocessed_sentence)}, 
    elmo_data)
analysis_dict

In [ ]:
candidates_lists = elmo40in.sccg([analysis_dict['tokenized_input_sentence']])
candidates_lists

In [ ]:
elmo40in.lm.retrieve_logits_of_particular_token(elmo_data, 1, 'профессиональнаякарьера')

In [ ]:
print(elmo40in.lm.retrieve_logits_of_particular_token(elmo_data, 1, 'профессиональная'))
print(elmo40in.lm.retrieve_logits_of_particular_token(elmo_data, 1, 'карьера'))


In [ ]:
hypos = estimate_the_best_s_hypotheses(data_analysis_dict=analysis_dict, min_advantage_treshold=1.0)
hypos

In [ ]:
hypos[0].text

# Evaluate

In [3]:
from evaluate import evaluate_spelling_corrector
import datetime as dt

In [4]:
DATA_PATH = 'data/'
DIALOG_DATA_PATH = DATA_PATH + 'dialog/'
# Train data
# TRAIN_ERRONEOUS_DATA = DIALOG_DATA_PATH + "source_sents.txt"
# TRAIN_GOLDEN_DATA = DIALOG_DATA_PATH + "corrected_sents.txt"

# Test data
TEST_ERRONEOUS_DATA = DIALOG_DATA_PATH + "test_sample_testset.txt"
TEST_GOLDEN_DATA = DIALOG_DATA_PATH + "corr_sample_testset.txt"


# Clean train
CLEAN_TRAIN_ERRONEOUS_DATA = DIALOG_DATA_PATH + "train_input_sentences.txt"
CLEAN_TRAIN_GOLDEN_DATA = DIALOG_DATA_PATH + "train_golden_sentences.txt"

In [5]:
# cleaned train!
with open(CLEAN_TRAIN_ERRONEOUS_DATA, 'r') as sents_file:
    erroneous_lines = sents_file.readlines()
    erroneous_lines = [line.lower().strip() for line in erroneous_lines]
    
with open(CLEAN_TRAIN_GOLDEN_DATA, 'r') as sents_file:
    golden_lines = sents_file.readlines()
    golden_lines = [line.lower().strip() for line in golden_lines]
    
    
# calculate number of sentnences with the same token length in TEST dataset
# with open(TEST_ERRONEOUS_DATA, 'r') as sents_file:
with open(TEST_ERRONEOUS_DATA, 'r') as sents_file:
    erroneous_lines_tst = sents_file.readlines()
    erroneous_lines_tst = [line.lower().strip() for line in erroneous_lines_tst]
    
# with open(TEST_GOLDEN_DATA, 'r') as sents_file:
with open(TEST_GOLDEN_DATA, 'r') as sents_file:
    golden_lines_tst = sents_file.readlines()
    golden_lines_tst = [line.lower().strip() for line in golden_lines_tst]

In [ ]:
# erroneous_lines
# golden_lines

# Load precalculated analysis dicts from file

In [ ]:
import json

# with open(DATA_PATH + "190923_analysis_dict_log_dialog_test_all_sents.txt") as f:
with open(DATA_PATH + "elmo40in2_train_data_analysis_dict_191002.json") as f:
    analysis_dicts_tst = json.load(f)
#     print(analysis_dicts_tst)
    
results_data = analysis_dicts_tst

# Prepare analysis dicts for sentences

In [ ]:
# loop over sentences that has the same number of tokens as in correct answer

start_dt = dt.datetime.now()
results_data = []
# TRAIN dataset:
input_sentences = erroneous_lines
etalon_sentences = golden_lines

# # TEST dataset:
# input_sentences = erroneous_lines_tst
# etalon_sentences = golden_lines_tst

for idx, each_error_line in enumerate(input_sentences):
#     if idx<300:continue

    analysis_dict = elmo40in.prepare_analysis_dict_for_sentence(each_error_line)

    analysis_dict['golden_sentence'] = etalon_sentences[idx]
    pprint.pprint(analysis_dict)
    results_data.append(analysis_dict)
    print("________________________________________")
#     if idx>400:
#         break
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)


## Parameters Grid Optimization

In [ ]:
# lets evaluate fixes model
# 1. lets produce famili of fixers
# max_num_fixes_params = (1,2,3,4,5)
# fix_treshold_params = 

from sklearn.model_selection import ParameterGrid
param_grid = {
#     'max_num_fixes': np.arange(1, 6), 
#     'min_advantage_treshold': np.linspace(0.0, 5.0, 11)}
# 'min_advantage_treshold': np.linspace(0.0, 1.0, 3)}
    'min_advantage_treshold': np.linspace(1.0, 1.0, 1)}
parameters_grid_list = list(ParameterGrid(param_grid))
print(list(ParameterGrid(param_grid)))

# fixes_maker(results_data[idx], max_num_fixes=5, fix_treshold=5, remove_s=True)

# Actually make fixes for particular SpellChecker Configuration

In [ ]:
results_data[1326]

In [ ]:
# len(results_data[355]['word_substitutions_candidates'])
# len(results_data[394]['word_substitutions_candidates'])
# len(results_data[948]['word_substitutions_candidates'])
len(results_data[1326]['word_substitutions_candidates'])

In [ ]:
results_data[1326]['word_substitutions_candidates']

In [ ]:
elmo40in.make_fixes(results_data[948], min_advantage_treshold= -0.1)

In [ ]:
results_data[948]

In [ ]:
# Sequential method for TRAIN dataset
# loop over sentences that has the same number of tokens as in correct answer
hypotheses = [[] for each_ in range(len(parameters_grid_list))]
filtered_erroneous_lines = []
filtered_golden_lines = []

for sent_idx, each_data in enumerate(results_data):
    print(sent_idx)
    for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
#         print(".")
#         print(each_estimator_param)
        sentence_hypothesis = elmo40in.make_fixes(each_data, **each_estimator_param)
        hypotheses[estimator_idx].append(sentence_hypothesis)
    filtered_erroneous_lines.append(each_data['input_sentence'])
    filtered_golden_lines.append(each_data['golden_sentence'])

# evaluate each estimator:
print("!!!!!!!!!!")
for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
    try:
        results = evaluate_spelling_corrector(filtered_erroneous_lines, 
                                              filtered_golden_lines, 
                                              hypotheses[estimator_idx])
        print(estimator_idx)
        print(each_estimator_param)
        print("f1:")
        print(results['f_measure'])
        print("precision:")
        print(results['precision'])
        print("_____")
    except Exception as e:
        print("Zero precision")
        pass
# pprint.pprint(results)

In [ ]:
# Print sentences with miscorrections for particular estimator
est_idx = 3
for num, each_res_dict in enumerate(results_data):
    if hypotheses[est_idx][num] != each_res_dict['golden_sentence']: 
        print("Input: %s" % each_res_dict['input_sentence'])
        print("Etaln: %s" % each_res_dict['golden_sentence'])
        print("Hypot: %s" % hypotheses[est_idx][num])
        print("Data Analysis Dict:" )
        pprint.pprint(results_data[num])
    print("___")

In [ ]:
hypotheses[4]

In [ ]:
# save data anlysis dict to file:
import json
with open(f'data/elmo40in2_train_data_analysis_dict_191002.json', 'w', encoding='utf-8') as outfile:
    json.dump(results_data, outfile, ensure_ascii=False, indent=2)


In [ ]:
######################################################################

In [ ]:

start_dt = dt.datetime.now()
results_data_tst = []
# # TEST dataset:
input_sentences = erroneous_lines_tst
etalon_sentences = golden_lines_tst

for idx, each_error_line in enumerate(input_sentences):
#     if idx<10:continue

    analysis_dict = elmo40in.prepare_analysis_dict_for_sentence(each_error_line)

    analysis_dict['golden_sentence'] = etalon_sentences[idx]
    pprint.pprint(analysis_dict)
    results_data_tst.append(analysis_dict)
    print("________________________________________")
#     if idx>20:
#         break
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)

##########################################################################################
# make fizxes for grid
# Sequential method for TEST dataset
# loop over sentences that has the same number of tokens as in correct answer
hypotheses_tst = [[] for each_ in range(len(parameters_grid_list))]
filtered_erroneous_lines = []
filtered_golden_lines = []

for sent_idx, each_data in enumerate(results_data_tst):
    for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
        print(sent_idx)
#         print(each_estimator_param)
        sentence_hypothesis = elmo40in.make_fixes(each_data, **each_estimator_param)
        hypotheses_tst[estimator_idx].append(sentence_hypothesis)
    filtered_erroneous_lines.append(each_data['input_sentence'])
    filtered_golden_lines.append(each_data['golden_sentence'])

# evaluate each estimator:
print("!!!!!!!!!!")
for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
    try:
        results = evaluate_spelling_corrector(filtered_erroneous_lines, 
                                              filtered_golden_lines, 
                                              hypotheses_tst[estimator_idx])
        print(estimator_idx)
        print(each_estimator_param)
        print("f1:")
        print(results['f_measure'])
        print("precision:")
        print(results['precision'])
        print("_____")
    except Exception as e:
        print("Zero precision")
        pass
# pprint.pprint(results)

In [ ]:
# save data anlysis dict to file:
import json
with open(f'data/elmo40in2_test_data_analysis_dict_191002.json', 'w', encoding='utf-8') as outfile:
    json.dump(results_data_tst, outfile, ensure_ascii=False, indent=2)


In [ ]:
print(results_data[9])
hypos = estimate_the_best_s_hypotheses(results_data[9], min_advantage_treshold=1)
print(hypos)
print(hypos[0].token_hypotheses)
elmo40in.make_fixes(results_data[9], min_advantage_treshold=2.0)


In [ ]:
# estimate score of the merged token
# {'tok_idx': (2, 3),
#    'tok_idx_start': 2,
#    'tok_idx_fin': 3,
#    'top_k_candidates': [{'token_str': 'мыла',
#      'token_merges': 1,
#      'error_score': -4.0}]}]}

np.log10(elmo_data[1, :, 49657:49667])

In [ ]:
##########################################################################################
# Sequential method for TEST dataset
# loop over sentences that has the same number of tokens as in correct answer
hypotheses_tst = [[] for each_ in range(len(parameters_grid_list))]
filtered_erroneous_lines = []
filtered_golden_lines = []

for sent_idx, each_data in enumerate(results_data_tst):
    for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
        print(sent_idx)
#         print(each_estimator_param)
        sentence_hypothesis = elmo40in.make_fixes(each_data, **each_estimator_param)
        hypotheses_tst[estimator_idx].append(sentence_hypothesis)
    filtered_erroneous_lines.append(each_data['input_sentence'])
    filtered_golden_lines.append(each_data['golden_sentence'])

# evaluate each estimator:
print("!!!!!!!!!!")
for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
    try:
        results = evaluate_spelling_corrector(filtered_erroneous_lines, 
                                              filtered_golden_lines, 
                                              hypotheses_tst[estimator_idx])
        print(estimator_idx)
        print(each_estimator_param)
        print("f1:")
        print(results['f_measure'])
        print("precision:")
        print(results['precision'])
        print("_____")
    except Exception as e:
        print("Zero precision")
        pass
# pprint.pprint(results)

In [ ]:
#####################################################################################

# Batchification Tests

In [ ]:
input_sentences = erroneous_lines
etalon_sentences = golden_lines
output_dicts = elmo40in.prepare_analysis_dict_for_sentences_batch(input_sentences[:20])
results=[]
for each_anal_dict in output_dicts:
    results.append(elmo40in.make_fixes(each_anal_dict, min_advantage_treshold=1.0))
results

In [6]:
list(map(lambda x: len(x.split()), erroneous_lines[600:630]))

[21,
 11,
 13,
 18,
 23,
 4,
 13,
 13,
 4,
 10,
 12,
 12,
 9,
 13,
 5,
 8,
 4,
 5,
 11,
 18,
 18,
 10,
 17,
 11,
 62,
 6,
 21,
 6,
 10,
 9]

In [8]:
#####################################################################################
# Train set

In [6]:
input_sentences = erroneous_lines
input_sentences

['очень классная тетка ктобы что не говорил',
 'может выгоднее втулку продать и купить колесо в сборе',
 'довольно большая часть пришедших сходила с дорожек и усаживалась на траву',
 'симпатичнейшое шпионское устройство такой себе гламурный фотоаппарат девушки бонда миниатюрная модель камеры superheadz clap camera',
 'опофеозом дня для меня сегодня стала фраза услышанная в новостях',
 'ну не было поста так небыло',
 'хотя странно когда я забирала к себе на выходные старого кота который живет у родителей да и собаку в придачу то такого концерта мой кот не устраивал',
 'думаю что лет через 10 ретроспективно просматривать это будет мне невероятно интересно',
 'зато я считаю что это будет полезно и для меня и для всех тех кто меня окружает ведь когда расстаешься с человеком на какое-то время то многое становится прозрачным я имею ввиду мы начинаем понимать какое место в нашей повседневности занимает этот человек',
 'пояним эту мысль',
 'она прямо бурлит у меня в крови тормошит какими-то со

In [6]:
# input_sentences = erroneous_lines[600:630]
# input_sentences = erroneous_lines[624:626]
input_sentences = erroneous_lines
start_dt = dt.datetime.now()
print("started at: " + str(start_dt))
output_sentences = elmo40in.process_sentences_batch(input_sentences, min_advantage_treshold=1.0, max_tokens_count=150)
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)

started at: 2019-10-16 18:12:22.414327
Total time for inference:
0:40:56.994986


In [7]:
print("!!!!!!!!!!")
etalon_sentences = golden_lines
try:
    results = evaluate_spelling_corrector(input_sentences, 
                                          etalon_sentences, 
                                          output_sentences)
    
    print("f1:")
    print(results['f_measure'])
    print("precision:")
    print(results['precision'])
    print("_____")
except Exception as e:
    print("Zero precision")
    pass

!!!!!!!!!!
Precision=78.84 Recall=67.52 FMeasure=72.74
1166 1479 1727
f1:
0.7273861509669372
precision:
0.7883705206220419
_____


In [17]:
erroneous_lines[624]

'настроене не понятное какоето солено-сладкое с одной стороны жалко расставаться с родителями и другими близкими людьми с другой радость от наконецто сбывающеся мечты можно и так это назвать хотя скорее стремление к более спокойной жизни ну и для меня лично есть огромная доля приключения в этом всем это как минимум интересно я всегда мечтал о таком путешествии вот так сижу обуреваемый чувствами'

In [9]:
# Print sentences with miscorrections for particular TRAIN

for num, inp_sent in enumerate(input_sentences):
    if output_sentences[num] != etalon_sentences[600+num]: 
        print("Input: %s" % inp_sent)
        print("Etaln: %s" % etalon_sentences[600+num])
        print("Hypot: %s" % output_sentences[num])
        print("Data Analysis Dict:" )
#         pprint.pprint(results_data[num])
    print("___")

Input: у меня так же как у пациента было много непонятного но игра состояла в том что я врач а он пациент
Etaln: у меня так же как у пациента было много непонятного но игра состояла в том что я врач а он пациент
Hypot: к меня также как в пациента было много непонятно о на игра состояла в том что я врач на он пациент
Data Analysis Dict:
___
Input: позаввчера пересматривал горбатую гору и в памяти всплыло сразу 2 человека
Etaln: позавчера пересматривал горбатую гору и в памяти всплыло сразу 2 человека
Hypot: позаввчера пересматривал горбатую гору и в память всплыло сразу и человека
Data Analysis Dict:
___
Input: а все же с огромным удовольствием я бы поехала в москву но невозможно
Etaln: а все же с огромным удовольствием я бы поехала в москву но невозможно
Hypot: в все же с огромным удовольствием я бы поехала в москву на невозможно
Data Analysis Dict:
___
Input: вобщем береш картинки из журналов вырезаешь интересующие темы делаешь из них коллаж и направляешь энергию для реализации желани

In [16]:
input_sentences

100

In [14]:
output_sentences

['очень классная тетка чтобы что не говорил',
 'может выгоднее втулку продать и купить колесо в сборе',
 'довольно большая часть пришедших сходила с дорожек и усаживалась на траву',
 'симпатичнейшое шпионское устройство такой себе гламурные фотоаппарат девушки бонда миниатюрная модель камеры superheadz clap camera',
 'опофеозом дня для меня сегодня стала фраза услышанная в новостях',
 'на не было поста так не было',
 'хотя странно когда я забирала к себе на выходные старого кота который живет с родителей до и собаки в придачу то такого концерта бойкот не устраивал',
 'думаю что лет через 10 ретроспективно просматривать это будет мне невероятно интересно',
 'за то я считаю что это будет полезно и для меня и для всех тех то меня окружает ведь когда расстаешься с человеком на какое-то время то многое становится прозрачным я имеют ввиду мы начинаем понимать какое место в нашей повседневности занимает этот человек',
 'пояним эту мысль',
 'на прямо бурлит у меня в крови тормошит какими-то со

In [11]:
etalon_sentences[:100]

['очень классная тетка кто бы что ни говорил',
 'может выгоднее втулку продать и купить колесо в сборе',
 'довольно большая часть пришедших сходила с дорожек и усаживалась на траву',
 'симпатичнейшее шпионское устройство такой себе гламурный фотоаппарат девушки бонда миниатюрная модель камеры superheadz clap camera',
 'апофеозом дня для меня сегодня стала фраза услышанная в новостях',
 'ну не было поста так не было',
 'хотя странно когда я забирала к себе на выходные старого кота который живет у родителей да и собаку в придачу то такого концерта мой кот не устраивал',
 'думаю что лет через 10 ретроспективно просматривать это будет мне невероятно интересно',
 'зато я считаю что это будет полезно и для меня и для всех тех кто меня окружает ведь когда расстаешься с человеком на какое-то время то многое становится прозрачным я имею ввиду мы начинаем понимать какое место в нашей повседневности занимает этот человек',
 'поясним эту мысль',
 'она прямо бурлит у меня в крови тормошит какими-то

In [ ]:
# before uptraining:
# !!!!!!!!!!
# Precision=74.72 Recall=58.37 FMeasure=65.54
# 1008 1349 1727
# f1:
# 0.6553966189856958
# precision:
# 0.7472201630837657
# _____

In [ ]:
#####################################################################################
# Test set

In [8]:
input_sentences = erroneous_lines_tst
start_dt = dt.datetime.now()
print("started at: " + str(start_dt))
output_sentences_tst = elmo40in.process_sentences_batch(input_sentences, min_advantage_treshold=1.0, max_tokens_count=120)
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)

# evaluate each estimator:
print("!!!!!!!!!!")
# for estimator_idx, each_estimator_param in enumerate(parameters_grid_list):
try:
    results = evaluate_spelling_corrector(input_sentences, 
                                          golden_lines_tst, 
                                          output_sentences_tst)
    
    print("f1:")
    print(results['f_measure'])
    print("precision:")
    print(results['precision'])
    print("_____")
except Exception as e:
    print("Zero precision")
    pass

started at: 2019-10-16 18:53:22.223708
Total time for inference:
0:47:27.313671
!!!!!!!!!!
Precision=75.74 Recall=65.98 FMeasure=70.52
1305 1723 1978
f1:
0.7052148068089704
precision:
0.7573998839233894
_____


# measure time advantage for batching with elmo

In [9]:
import datetime as dt

In [10]:
# if you use 2 or 3 setences in a batch then consequent run is more effective!
# but if you take >=10 sentences, then batching is advantageous
# sentences = ["дама рыла ламу", 
#              "на реконструкции дворца понятно что обозлились слишком хороше для киева сделал",
#             "ты сам себе создаешь проблемы пойми что мир не будет приклонятся перед тобой и притиратся к твоим взглядам",
#             "схездил птом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "схездил потом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "схездил потом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "но даже когда мы приблизились к нижнему уровню замка я поверить не могла что он такой огромный как показывалось на карте",
#             "давно стоит понять что в этой жизни никто не зделает так как лутче тебе",
#              "давно стоит понять что в этой жизни никто не делает так как лутче тебе.",
#              "дама рыла ламу", 
#              "на реконструкции дворца понятно что обозлились слишком хороше для киева сделал",
#             "ты сам себе создаешь проблемы пойми что мир не будет приклонятся перед тобой и притиратся к твоим взглядам",
#             "схездил птом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "схездил потом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "схездил потом в ркб оказалось что на нем 3 царапины купил мази и капли",
#              "но даже когда мы приблизились к нижнему уровню замка я поверить не могла что он такой огромный как показывалось на карте",
#             "давно стоит понять что в этой жизни никто не зделает так как лутче тебе",
#              "давно стоит понять что в этой жизни никто не делает так как лутче тебе.",
#              "на реконструкции дворца понятно что обозлились слишком хороше для киева сделал",
#             "ты сам себе создаешь проблемы пойми что мир не будет приклонятся перед тобой и притиратся к твоим взглядам",
#             ]

sentences = erroneous_lines[:15]
tok_sents_wrapped = elmo40in.lm.tokenize_sentence_batch(sentences)


############################

start_dt2 = dt.datetime.now()
elmo40in.lm.elmo_lm(tok_sents_wrapped)
fin_dt2 = dt.datetime.now()
print("Total time for inference batchy:")
print(fin_dt2-start_dt2)

#################################
start_dt = dt.datetime.now()
for idx, each_sent in enumerate(sentences):
    elmo40in.lm.elmo_lm(tok_sents_wrapped[idx])
fin_dt = dt.datetime.now()
print("Total time for inference iteratively:")
print(fin_dt-start_dt)

Total time for inference batchy:
0:00:19.658987
Total time for inference iteratively:
0:00:38.576642


In [ ]:
##########################################################################

In [30]:
import gc
gc.collect()

4450961

In [10]:
! pip install guppy3

In [5]:
from guppy import hpy
h = hpy()
print(h.heap())

Partition of a set of 18421019 objects. Total size = 2655209614 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0 9399731  51 1252770278  47 1252770278  47 numpy.ndarray
     1 4750502  26 465133410  18 1717903688  65 str
     2 425243   2 462707992  17 2180611680  82 dict (no owner)
     3 276195   1 165531040   6 2346142720  88 set
     4 286164   2 144947576   5 2491090296  94 list
     5 2088585  11 58495372   2 2549585668  96 int
     6 357031   2 29089712   1 2578675380  97 tuple
     7 400639   2 12820448   0 2591495828  98 numpy.int64
     8 142740   1 11545386   0 2603041214  98 bytes
     9  72109   0 10439832   0 2613481046  98 types.CodeType
<2036 more rows. Type e.g. '_.more' to view.>


In [1]:
# from guppy3 import hpy

ModuleNotFoundError: No module named 'guppy3'