In [1]:
import pprint
import numpy as np
from spelling_correction_models.elmo_40in_spelling_corrector.elmo_40in2_spelling_corrector import ELMO40in2SpellingCorrector
from copy import deepcopy
from spelling_correction_models.elmo_40in_spelling_corrector.helper_fns import *
from evaluate import evaluate_spelling_corrector
import datetime as dt
import pandas as pd

/home/alx/Cloud/spell_corr/py_spelling_corrector


In [2]:
# from language_models.elmolm_on_torch import ELMOLMTorch
# elmo40in = ELMO40in2SpellingCorrector(mini_batch_size=10, language_model=torch_lm)
# torch_lm = ELMOLMTorch()
# torch_elmo40in = ELMO40in2SpellingCorrector(mini_batch_size=10, language_model=torch_lm)

tf_elmo40in = ELMO40in2SpellingCorrector(mini_batch_size=10)

Init LetterCaser.
Init language_model.


[nltk_data] Downloading package punkt to /home/alx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/alx/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /home/alx/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/alx/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
2019-10-29 13:55:38.150 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:21: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2019-10-29 13:55:38.150 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:21: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO 

/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news
['/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003.meta']
/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003.meta
/home/alx/Cloud/spell_corr/py_spelling_corrector/bidirectional_lms/elmo_ru_news/model.ckpt-0003


2019-10-29 13:55:42.41 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:40: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-10-29 13:55:42.41 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-29 13:55:42.374 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:43: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2019-10-29 13:55:42.376 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Cloud/spell_corr/bilm-tf/bilm/training.py:158: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instea

USING SKIP CONNECTIONS


2019-10-29 13:55:42.815 WARNING in 'tensorflow'['ag_logging'] at line 145: Entity <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7fd0cc336eb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method LSTMCell.call of <tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x7fd0cc336eb8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-10-29 13:55:42.844 WARNING in 'tensorflow'['deprecation_wrapper'] at line 119: From /home/alx/Workspace/DeepPavlov/deeppavlov/models/bidirectional_lms/elmo/utils.py:52: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-10-29 13:55:42.933 WARNING in 'tensorflow'['deprecation'] at line 323: From /home/alx/Cloud/.venv3gpu/lib/python3.6/site-packages/tensorflow/python/training/save

Init spelling_correction_candidates_generator.
Initialization Completed.


In [ ]:
# Evaluate

In [2]:
DATA_PATH = 'data/'
DIALOG_DATA_PATH = DATA_PATH + 'dialog/'
ABK_DATA_PATH = DATA_PATH + 'abk/'
# Train data
# TRAIN_ERRONEOUS_DATA = DIALOG_DATA_PATH + "source_sents.txt"
# TRAIN_GOLDEN_DATA = DIALOG_DATA_PATH + "corrected_sents.txt"

# Test data
TEST_ERRONEOUS_DATA = DIALOG_DATA_PATH + "test_sample_testset.txt"
TEST_GOLDEN_DATA = DIALOG_DATA_PATH + "corr_sample_testset.txt"


# Clean train
CLEAN_TRAIN_ERRONEOUS_DATA = DIALOG_DATA_PATH + "train_input_sentences.txt"
CLEAN_TRAIN_GOLDEN_DATA = DIALOG_DATA_PATH + "train_golden_sentences.txt"

SPELLCHECKER_DATA_500_CSV = ABK_DATA_PATH + "spell_checker_data500.csv"

In [4]:
df500 = pd.read_csv(SPELLCHECKER_DATA_500_CSV, header=0, delimiter='\t')

In [5]:
df500

original_text  \
0    Кто такие химкинские заложники Слышал что како...   
1    Что почитать из нон-фикшена с интересными факт...   
2    121 год Московской Канализации прощай немытая ...   
3    Вопрос куда поехать с подругой на ДР Московска...   
4    Кто худел при помощи Редуксина поделитесь опыт...   
5    как гастеры умудряются за зарплату 15 тыщь сни...   
6    Что за изогнутые трубки немного ниже пояса у в...   
7    в ЕС-овские звгранпаспорта никакие штампы в Ро...   
8    Можно ли завести в дом воду из колодца с непит...   
9    Бывший прислал песню О чём она на ваш взгляд Н...   
10   Помогите написать рассказ о главном герое в ра...   
11   Дадут конечно счаз народ кредиты плохо берут п...   
12   пасаны шестерят на зоне и на тазах понтуются п...   
13   в моей молодости был зеленстрой- уход обрезка ...   
14   гос рекрутинговое агенство это центр занятости...   
15   каждое кадровое агенство - лохотрон И чем мощн...   
16   Помогите выбрать мотоцикл эндуро без птс Бюдже...   
17   как у большинства людей получается на работе х...   
18   А вы ИЗБАЛОВАННЫЙ человек Нуу так если объекти...   
19   Блин я не знаю как понимать своего парня Когда...   
20   Здрасьте Где можно хорошо провести время Кочев...   
21   как найти надежную фирму по регистрации гражда...   
22   Я раньше юзал Terteus Безлимитная подписка сто...   
23   Сермянка мордовская-эрзя деревня Чардымского с...   
24   Это не редактор это скришот Инстаграма или чег...   
25   Не заметил разницы с растяжкой и без но по иде...   
26   Необходимо приложение или программа на андройд...   
27   Какая комисия киви кошелька на данный момент 2...   
28   Как позвонить на номер 380445930672 с номера 3...   
29   надоело ездить на мотоцикле дождь заи л хочу к...   
..                                                 ...   
470  Пожалуйста кто может скиньте ссылку где можно ...   
471  Мозила до определенной версии сафари яндекс та...   
472  если он сломает мой замок что ему будет в мили...   
473  Посоветуйте пожалуйста какое нибудь приложение...   
474  Мне 14 и я люблю смотреть 18 и лазать по прило...   
475  какой кальян из дешовых пасоветуите купить как...   
476  Нет прекрасней и полезней Венерических болезне...   
477  Учился до 5 класса отличником а в 6 хорошистом...   
478  какими тракторами я могу упровлять с удоставир...   
479  На работу устраиватся и выдали карту и попроси...   
480  возможно какое то приложение является админист...   
481  Чего объяснять Из каждых ДВУХ цифр пятеричной ...   
482  Подскажите где взять фото с ночного клуба Stud...   
483  Подскажите как сделать ключи анимации в вегасе...   
484  Своровали небось вегас Купите лицензионную вер...   
485  подскажите люди добрые какой нибудь фоторедакт...   
486  Нуу присяду на что-нить и прям тютелька в тюте...   
487  img src otvet imgsmail ru download 238370794 2...   
488  Можно ли в Вансах кедах ходить на физру Или он...   
489  ПОЖАЛУЙСТО ПОМОГИТЕ ПТИЧИЙ РЫНОК УКРАИНА ХАРЬК...   
490  Лучше для пластики хатха йога для ре ласации -...   
491  Россиянин после инфаркта в украине куда обрати...   
492  Здравствуйте Скажите а какие документы нужны д...   
493  Все кто меня обижал в жизни попадали в дтп как...   
494  как очистить 200л бочку от дифенилметандиизоци...   
495  Служба поддержки Алиэкспресс даёт советы котор...   
496  здесь жука из загреба предлагает фирма из герм...   
497  Часто работаю дома как надо расположить стол л...   
498  для начала без разницы если увлечет то там уже...   
499  Сколько месяцев кактусы Эхинокактус Грузони 5 ...   

                                        corrected_text  
0    Кто такие химкинские заложники Слышал что како...  
1    Что почитать из нон-фикшена с интересными факт...  
2    121 год Московской Канализации прощай немытая ...  
3    Вопрос куда поехать с подругой на ДР Московска...  
4    Кто худел при помощи Редуксина поделитесь опыт...  
5    как гастеры умудряются за зарплату 15 тысяч сн...  
6    Что за изогнутые трубки немного ниже поя

In [6]:
source_sentences = df500['original_text'].values
etalon_sentences = df500['corrected_text'].values

In [7]:
# input_sentences = erroneous_lines[600:630]
# input_sentences = erroneous_lines[624:626]
input_sentences = source_sentences
start_dt = dt.datetime.now()
print("started at: " + str(start_dt))
output_sentences = elmo40in.process_sentences_batch(input_sentences, min_advantage_treshold=1.0, max_tokens_count=150)
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)

started at: 2019-10-29 13:58:20.852418


NameError: name 'elmo40in' is not defined

In [8]:
print("!!!!!!!!!!")
etalon_sentences = etalon_sentences
try:
    results = evaluate_spelling_corrector(input_sentences, 
                                          etalon_sentences, 
                                          output_sentences)
    
    print("f1:")
    print(results['f_measure'])
    print("precision:")
    print(results['precision'])
    print("_____")
except Exception as e:
    print("Zero precision")
    pass

!!!!!!!!!!
Precision=49.69 Recall=45.47 FMeasure=47.49
241 485 530
f1:
0.4748768472906404
precision:
0.49690721649484537
_____


In [11]:
# Print sentences with miscorrections for particular estimator
for num, out_sent in enumerate(output_sentences):
    if out_sent != etalon_sentences[num]: 
        print("Input: %s" % input_sentences[num])
        print("Etaln: %s" % etalon_sentences[num])
        print("Hypot: %s" % out_sent)
#         print("Data Analysis Dict:" )
#         pprint.pprint(results_data[num])
    print("___")

___
Input: Что почитать из нон-фикшена с интересными фактами Не совсем к слову понимаю точные науки
Etaln: Что почитать из нон-фикшена с интересными фактами Не совсем к слову понимаю точные науки
Hypot: Что почитать и нон-фикшена с интересными фактами Не совсем к слову понимаю точные науки
___
Input: 121 год Московской Канализации прощай немытая Европа щас по 94 8 ФМ передача идёт
Etaln: 121 год Московской Канализации прощай немытая Европа сейчас по 94 8 ФМ передача идёт
Hypot: 121 год Московской Канализации прощай немытая Европа щас по 94 8 М передача идёт
___
Input: Вопрос куда поехать с подругой на ДР Московская область Красногорский р-он г Нахабино Красногорск
Etaln: Вопрос куда поехать с подругой на ДР Московская область Красногорский район г Нахабино Красногорск
Hypot: Вопрос куда поехать с подругой надо Московская область Красногорский р-он г Нахабино Красногорск
___
___
Input: как гастеры умудряются за зарплату 15 тыщь снимать жилье еще отправлять деньги домой и жить на них
Eta

## Evaluate TF_kuznetsov model


In [8]:
# input_sentences = erroneous_lines[600:630]
# input_sentences = erroneous_lines[624:626]
input_sentences = source_sentences
start_dt = dt.datetime.now()
print("started at: " + str(start_dt))
output_sentences = tf_elmo40in.process_sentences_batch(input_sentences, min_advantage_treshold=1.0, max_tokens_count=150)
fin_dt = dt.datetime.now()
print("Total time for inference:")
print(fin_dt-start_dt)

started at: 2019-10-29 13:58:41.599197
dynamic batch size: 6
[[[[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]]


 [[[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]

  [[258. 256. 259. ... 260. 260. 260.]]]


 [[[258. 208. 180. ... 260. 260. 260.]]

  [[258. 208. 189. ... 260. 260. 260.]]

  [[258. 208. 189. ... 260. 260. 260.]]

  [[258. 209. 129. ... 260. 260. 260.]]

  [[258. 208. 188. ... 260. 260. 260.]]

  [[258. 208. 178. ... 260. 260. 260.]]]


 ...


 [[[258. 209. 132. ... 260. 260. 260.]]

  [[258. 259. 260. ... 260. 260. 260.]]

  [[258. 259. 260. ... 260. 260. 260.]]

  [[258. 259. 260. ... 260. 260. 260.]]

  [[258. 259. 260. ... 2

MemoryError: 

In [ ]:
print("!!!!!!!!!!")
etalon_sentences = etalon_sentences
try:
    results = evaluate_spelling_corrector(input_sentences, 
                                          etalon_sentences, 
                                          output_sentences)
    
    print("f1:")
    print(results['f_measure'])
    print("precision:")
    print(results['precision'])
    print("_____")
except Exception as e:
    print("Zero precision")
    pass

## score by yandex

In [12]:
import requests

def ya_correction(text):
    url = 'https://speller.yandex.net/services/spellservice.json/checkText'
    r = requests.post(url, data=f'text={text}'.encode(), headers={'Content-Type': 'application/x-www-form-urlencoded'})
    corrected = text
    try:
        for c in reversed(r.json()):
            if c.get('s'):
                corrected = corrected[:c['pos']] + c['s'][0] + corrected[c['pos'] + c['len']:] 
    except:
        print(text)
        raise
    return corrected

In [13]:
ya_hypotheses = []
from tqdm import tqdm
for each_sent in tqdm(input_sentences):
    ya_hypotheses.append(ya_correction(each_sent))

2019-10-29 13:06:36.343 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:37.72 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 377
2019-10-29 13:06:37.84 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:37.235 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:06:37.247 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:37.392 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:06:37

2019-10-29 13:06:41.972 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:42.88 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:06:42.99 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:42.265 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 149
2019-10-29 13:06:42.284 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:42.464 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 153
2019-10-29 13:06:

2019-10-29 13:06:47.432 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:47.753 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 240
2019-10-29 13:06:47.768 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:47.905 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:06:47.921 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:48.368 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 943
2019-10-29 13:0

2019-10-29 13:06:53.268 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:53.492 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 178
2019-10-29 13:06:53.506 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:53.665 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:06:53.678 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:53.841 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 155
2019-10-29 13:0

2019-10-29 13:06:59.442 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:59.692 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 346
2019-10-29 13:06:59.711 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:06:59.937 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 143
2019-10-29 13:06:59.947 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:00.76 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07

2019-10-29 13:07:05.329 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:05.496 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 186
2019-10-29 13:07:05.500 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:05.741 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 210
2019-10-29 13:07:05.756 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:06.1 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 167
2019-10-29 13:0

2019-10-29 13:07:11.15 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:11.332 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 369
2019-10-29 13:07:11.345 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:11.504 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:11.524 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:11.725 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:1

2019-10-29 13:07:16.351 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:16.480 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:16.493 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:16.749 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 215
2019-10-29 13:07:16.762 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:16.905 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:

2019-10-29 13:07:21.631 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:21.864 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 260
2019-10-29 13:07:21.877 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:22.123 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 None
2019-10-29 13:07:22.137 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:22.410 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 346
2019-10-29 1

2019-10-29 13:07:26.718 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:26.843 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:26.857 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:27.124 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 628
2019-10-29 13:07:27.132 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:27.335 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 119
2019-10-29 13:0

2019-10-29 13:07:31.579 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:31.721 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:31.740 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:31.888 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:31.901 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:32.101 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 212
2019-10-29 13:07:

2019-10-29 13:07:36.662 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:36.787 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:36.801 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:36.928 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:36.942 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:37.67 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:37.

2019-10-29 13:07:41.879 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 161
2019-10-29 13:07:41.892 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:42.165 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 435
2019-10-29 13:07:42.178 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:42.462 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 966
2019-10-29 13:07:42.465 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13

2019-10-29 13:07:47.456 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 173
2019-10-29 13:07:47.459 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:47.616 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:07:47.619 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:47.830 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 336
2019-10-29 13:07:47.833 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:0

2019-10-29 13:07:51.896 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 159
2019-10-29 13:07:51.899 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:52.41 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 113
2019-10-29 13:07:52.44 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:52.198 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 158
2019-10-29 13:07:52.201 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:0

2019-10-29 13:07:56.701 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 199
2019-10-29 13:07:56.723 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:56.905 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 155
2019-10-29 13:07:56.910 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:07:57.90 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 155
2019-10-29 13:07:57.109 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:

2019-10-29 13:08:01.796 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 165
2019-10-29 13:08:01.805 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:01.965 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 579
2019-10-29 13:08:01.973 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:02.221 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 149
2019-10-29 13:08:02.234 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13

2019-10-29 13:08:10.219 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 222
2019-10-29 13:08:10.229 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:10.391 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 95
2019-10-29 13:08:10.395 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:10.641 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 262
2019-10-29 13:08:10.650 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:

2019-10-29 13:08:15.361 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:08:15.374 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:15.636 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 310
2019-10-29 13:08:15.649 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:15.895 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 395
2019-10-29 13:08:15.909 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:0

2019-10-29 13:08:21.758 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 760
2019-10-29 13:08:21.780 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:21.963 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 2
2019-10-29 13:08:21.976 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:08:22.109 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 396: https://speller.yandex.net:443 "POST /services/spellservice.json/checkText HTTP/1.1" 200 125
2019-10-29 13:08:22.123 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 815: Starting new HTTPS connection (1): speller.yandex.net:443
2019-10-29 13:0

In [14]:
try:
    results = evaluate_spelling_corrector(input_sentences, 
                                          etalon_sentences, 
                                          ya_hypotheses)
    
    print("f1:")
    print(results['f_measure'])
    print("precision:")
    print(results['precision'])
    print("_____")
except Exception as e:
    print("Zero precision")
    pass

Precision=70.65 Recall=63.58 FMeasure=66.93
337 477 530
f1:
0.6693147964250248
precision:
0.7064989517819706
_____


In [16]:
# Print sentences with miscorrections for particular estimator
for num, out_sent in enumerate(ya_hypotheses):
    if out_sent != etalon_sentences[num]: 
        print("Input: %s" % input_sentences[num])
        print("Etaln: %s" % etalon_sentences[num])
        print("Hypot: %s" % out_sent)
#         print("Data Analysis Dict:" )
#         pprint.pprint(results_data[num])
    print("___")

Input: Кто такие химкинские заложники Слышал что какойто дело завели а что случилось из за чего незнаю
Etaln: Кто такие химкинские заложники Слышал что какой-то дело завели а что случилось из-за чего не знаю
Hypot: Кто такие химкинские заложники Слышал что какой то дело завели а что случилось из за чего не знаю
___
___
Input: 121 год Московской Канализации прощай немытая Европа щас по 94 8 ФМ передача идёт
Etaln: 121 год Московской Канализации прощай немытая Европа сейчас по 94 8 ФМ передача идёт
Hypot: 121 год Московской Канализации прощай немытая Европа щас по 94 8 ФМ передача идёт
___
Input: Вопрос куда поехать с подругой на ДР Московская область Красногорский р-он г Нахабино Красногорск
Etaln: Вопрос куда поехать с подругой на ДР Московская область Красногорский район г Нахабино Красногорск
Hypot: Вопрос куда поехать с подругой на ДР Московская область Красногорский р-он г Нахабино Красногорск
___
___
Input: как гастеры умудряются за зарплату 15 тыщь снимать жилье еще отправлять де